const topPlayersCategory: string[] = [
    "goals",
    "goal_assist",
    "total_pass",
    "clean_sheet",
    "appearances",
    "mins_played",
    "yellow_card",
    "red_card",
    "touches",
    "touches",
    "total_scoring_att",
    "hit_woodwork",
    "big_chance_missed",
    "total_offside",
    "total_tackle",
    "fouls",
    "dispossessed",
    "own_goals",
    "total_clearance",
    "clearance_off_line",
    "saves",
    "penalty_save",
    "total_high_claim",
    "punches",
];

export default topPlayersCategory;
