const topClubsCategory: Array<string> = [
    "wins",
    "losses",
    "touches",
    "own_goals",
    "total_yel_card",
    "total_red_card",
    "goals",
    "total_pass",
    "total_scoring_att",
    "total_offside",
    "hit_woodwork",
    "big_chance_missed",
    "total_tackle",
    "total_clearance",
    "clearance_off_line",
    "dispossessed",
    "clean_sheet",
    "saves",
    "penalty_save",
    "total_high_claim",
    "punches",
];

export default topClubsCategory;
